# Application Configuration
spring.application.name=ecolink-api

# Server Configuration
server.port=8080

# MongoDB Configuration
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=ecolink_db

# Logging Configuration
logging.level.root=INFO
logging.level.com.ecolink.api=DEBUG
